---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: fc36 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh fc36 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la fc36
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: el9 s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el9 s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la el9
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy amd64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la jammy
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy arm64 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy arm64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la jammy
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy armv7 build
platform:
  arch: arm64
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy armv7 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la jammy
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy riscv64 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy riscv64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la jammy
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la jammy
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: jammy s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh jammy s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la jammy
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bullseye 386 build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye 386 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la bullseye
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bullseye mips64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye mips64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la bullseye
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bullseye ppc64le build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye ppc64le 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la bullseye
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
---
clone:
  depth: 1
image_pull_secrets:
- dockerconfigjson
kind: pipeline
name: bullseye s390x build
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh bullseye s390x 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: registry.sean.farm/honda-builder
  name: build
- commands:
  - ls -la bullseye
  image: registry.sean.farm/honda-builder
  name: list
trigger:
  event:
  - push
  - tag
type: docker
